version: '3.8'


services:

  web:
    build: ./dcelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dcelery/:/usr/src/app/
    ports: 
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=(k2%rddp=8v&q&&9s$c!!^!&ja3cc7kb*#9r+26l=3ingfuznx
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    
  
  celery:
    build: ./dcelery
    command: celery --app=dcelery worker --loglevel=info
    volumes:
      - ./dcelery/:/usr/src/app/
    environment: 
      - DEBUG=1
      - SECRET_KEY=(k2%rddp=8v&q&&9s$c!!^!&ja3cc7kb*#9r+26l=3ingfuznx
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
  

  redis:
    image: redis:7-alpine
    